package wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2017-07-19T22:25:07.182+08:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "IServiceWsImpService", 
                  wsdlLocation = "http://localhost:8080/webPortalsEjb-1.0/IServiceWsImp?wsdl",
                  targetNamespace = "http://service.ok3w/") 
public class IServiceWsImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ok3w/", "IServiceWsImpService");
    public final static QName IServiceWsImpPort = new QName("http://service.ok3w/", "IServiceWsImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webPortalsEjb-1.0/IServiceWsImp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IServiceWsImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webPortalsEjb-1.0/IServiceWsImp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IServiceWsImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IServiceWsImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceWsImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IServiceWsImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IServiceWsImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IServiceWsImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IServiceWsImp
     */
    @WebEndpoint(name = "IServiceWsImpPort")
    public IServiceWsImp getIServiceWsImpPort() {
        return super.getPort(IServiceWsImpPort, IServiceWsImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceWsImp
     */
    @WebEndpoint(name = "IServiceWsImpPort")
    public IServiceWsImp getIServiceWsImpPort(WebServiceFeature... features) {
        return super.getPort(IServiceWsImpPort, IServiceWsImp.class, features);
    }

}
